warp-contracts/academy

redstone-academy-docs/docs/intro.md

"having a reliable".
"give both a basic and more advanced".
"no matter what their background".

Mark-corrections[3]

---

redstone-academy-docs/docs/loot/deployment/deployment.md

"The smart contract deployment code is very similar to the one that we used in the testing script. You can see an example of the deployment script in [redstone-academy-loot/src/tools/deploy-contracts.js](https://github.com/redstone-finance/redstone-academy/blob/main/redstone-academy-loot/src/tools/deploy-contracts.js)."

Mark-corrections[3,]

---

redstone-academy-docs/docs/loot/tests/testing-contract.md

"We strongly recommend you implement tests for all your smart contracts. It's generaly a good practice and it will help you to avoid simple bugs before deploying contracts to blockchain."
"And it allows us to test SmartWave contracts without spending AR tokens."

Mark-corrections[3,8,]

---

redstone-academy-docs/docs/loot/implementation/contract-logic.md

"As you can see the `handle` function has 2 arguments that will be fulfilled with values during interaction with the contract. The `state` argument will contain (guess what) the state and the `action` argument will contain information about the interaction function name and (optionally) its arguments."

Mark-corrections[14,]

---

redstone-academy-docs/docs/loot/implementation/contract-state.md

"The first 2 things you should think about before implementing a SmartWeave contract are:"
"Initially the `assets` object will be empty. But it will be filling with the newly generated assets and pointing to their owners. This state structure allows us to quickly understand who owns an asset or switch the ownership."

Mark-corrections[7,17,]

---

redstone-academy-docs/docs/loot/introduction/intro.md

"This tutorial shows how to implement a simple loot contract on the SmartWeave protocol."
"We will implement a simple [LOOT](https://www.lootproject.com/)-like contract, which allows us to generate and transfer different magical assets, for example `black silver sword` or `blue gold crown`. Each asset will be unique and can belong to only one wallet at a time."

Mark-corrections[3,7,]

---

redstone-academy-docs/docs/pst/smartweave-in-browser/interacting-with-contract.md

"We are displaying all the balances in the `BalancesList` component. We have access to the list thanks to `state` property we defined in the store in the Preparations section. Now all we need to do is find a way to properly mint some FC tokens to the wallet and transfer tokens between addresses."
"Finally, set the new balances list by calling `currentState` method:"

Mark-corrections[3,46,]

---

redstone-academy-docs/docs/pst/frontend-environment/frontend-environment.md

"Here are two basic commands which will help you build your project and running it in development environment."
"2. [challenge/src/pst-contract.ts](https://github.com/redstone-finance/redstone-academy/blob/main/redstone-academy-pst/challenge/src/pst-contract.ts) - here we define Arweave and SmartWeave instances and export them."
"3. [challenge/src/deployed-contracts.ts](https://github.com/redstone-finance/redstone-academy/blob/main/redstone-academy-pst/challenge/src/deployed-contracts.ts) - here we indicate deployed contract id."
"6. [challenge/src/components](https://github.com/redstone-finance/redstone-academy/blob/main/redstone-academy-pst/challenge/src/components) - all the components which are key Vue features to encapsulate reusable code."
"You don't need any frontend skills to …

Mark-corrections[5,16,18,24,32,]

---

redstone-academy-docs/docs/pst/deployment/deployment.md

"As mentioned earlier, we will deploy our contract to the RedStone public testnet. You will notice that it is very similiar to how we deployed the contract to ArLocal. We just need to write a NodeJS script which will generate and fund the Arweave wallet, read, contract source and initial state files and deploy the contract to the testnet. At the end of this chapter, I'll show you how to repeat all these steps in order to deploy contract to Arweave mainnet."
"Like the last time - firstly, we will need to declare variables that will be needed in the script. Head to [challenge/src/tools/deploy-test-contract.ts](https://github.com/redstone-finance/redstone-academy/blob/main/redstone-academy-pst/challenge/src/tools/deploy-test-contract.ts) and add the following code:"
"Then, we need to …

Mark-corrections[5,7,22,78,94,101,105,121,132]

---

redstone-academy-docs/docs/pst/tests/execution.md

"We will write a couple of tests which will help us understand some basics about interacting with the contract. After writing each test you should run the correct script from the previous section (node or browser one) to see if it works correctly."
"Let's start with reading the contract's state. Add the following code to `should read pst state and balance data` test. If you've set other addresses or balances in the initial state you will of course need to change them accordingly."
"We are using SDK's `currentState` method which reads the current state of our contract. We are also using PST's specific method - `currentBalance` which takes the target wallet as an argument and read its current balance. Underneath, it simply returns the "view" of the state, computed by the SWC - ie. the …

Mark-corrections[3,7,21,25,37,39,43,65,99]

---

redstone-academy-docs/docs/pst/tests/preparations.md

"It is more than important to carefully test your contract before deploying it to the blockchain. We will write a few tests and execute them in a server environment as well as in a browser using Jest. Throughout this process you will get to know a couple of important **ArweaveJS** and **RedStone Smartweave SDK** methods".
"We initialize ArLocal - a local server resembling the real Arweave network - on port 1820 (the default one is 1984) and start the instance. Then, we initialize Arweave by pointing to the running local testnet".
"Logging is helpful not only during the development process but also when interacting with the contract as it gives some indication of what is happening and what errors have occured. RedStone Smartweave SDK has seven levels of logging, you can view all logging …

Mark-corrections[3,33,41,48,56,65,76,116,153,161,163,167,191]

---

redstone-academy-docs/docs/pst/tests/networks.md

"Before we start writing tests, we need to understand the different types of networks on Arweave blockchain".
"Instead of heading to arweave.net you can request and query nodes directly. Nodes are Arweave users with large storage spaces on their hard drives, they connect with the Arweave network and store data for others. You can use exactly the same API as for the gateway. A list of all currently running nodes can be found on [arweave.net/peers](https://arweave.net/peers)".
"Unlike mainnet, testnet means that the network is not running on its full capacity. It is used by developers to test different kind of actions and features before posting them to mainnet".
"1. **ArLocal** - is a local server which resembles Arweave mainnet. You need to run it locally on your computer".
"2. **RedStone …

Mark-corrections[3,20,29,33,41,47]

---

redstone-academy-docs/docs/pst/writing-pst-contract/contract-source.md

"Time for an explanation".
"The above function will help us read the balance of the inidicated target address. It takes two arguments - contract computed state and destructured contract action which give us input to the interaction. Remember that we have three possible options to be returned from the interactions? In the above interaction we added two of them - thanks to simple error handling we can return `ContractError` or result".
"This one will help us minting some tokens to the caller's address. It takes two arguments - contract state and the destructured caller of the interaction as well as the input to the interaction. It adds tokens to the caller's address. It can throw `ContractError` exception or return contract's state".
"And the last one - the core function of our contract …

Mark-corrections[43,89,121,167,208,212,214,245,]

---

redstone-academy-docs/docs/pst/writing-pst-contract/initial-state.md

"To obtain good structure we will use the power of Typescript and prepare some types first. Head to [redstone-academy-pst/challenge/src/contracts/types/types.ts](https://github.com/redstone-finance/redstone-academy/tree/main/redstone-academy-pst/challenge/src/contracts/types/types.ts) and let's start writing!"
"`PstState` represents the contract's current state. Its shape is not defined by any rules and it is the developer who decides what the state will look like. In case of our implementation it will consist of four properties:"
"Now we have it typed, we can write the initial state for our contract. Head to [redstone-academy-pst/challenge/src/contracts/initial-state.json](https://github.com/redstone-finance/redstone-academy/tree/main/redstone-academy-pst/challenge/src/contracts/initial-s …

Mark-corrections[9,24,33]

---

redstone-academy-docs/docs/pst/writing-pst-contract/preparations.md

"Now that we have a basic understanding of what PSTs are, we can dive into the code".
"We have prepared for you some basic setups consiting of Vue2 and Bootstrap for the frontend part, Typescript, Jest and ts-jest for tests, and ts-node for running scripts. You can of course use other tools/frameworks. However, we recommend using the ones we have prepared while going through this tutorial. You will need to write some code during the tutorial so the application is able to work. We advise you to read the instructions first and then try on your own. You can always view the final solution in [redstone-academy-pst/final](https://github.com/redstone-finance/redstone-academy/tree/main/redstone-academy-pst/final)".
"Install all dependencies connected with SmartWeave contracts. Do not worry, you …

Mark-corrections[3,4,12]

---

redstone-academy-docs/docs/pst/introduction/intro.md

"In this tutorial we're going to learn how to build a simple PST (Profit Sharing Token) application. Our main token will be Federation Credits which are monetary units used by the United Federation of Planets. You can read some more about this fictional unit in the [Star trek fandom wiki](https://memory-alpha.fandom.com/wiki/Federation_credit). In order to achieve that, we will write our first PST contract. After writing some tests, we will deploy it to the [RedStone public testnet](https://testnet.redstone.tools/). It will let us mint some tokens as well as transfer them between addresses and read current balances".
"We will also give you some advice of how to deploy the contract to the Arweave mainnet".
"We've already deployed final versions of the PST contract and application".
"You …

Mark-corrections[7,9,20,21,

---

redstone-academy-docs/docs/elementary/smartweave.md

"In general, smart contracts are programs"
"They automatically execute"
"Smart contracts are deployed to the blockchain and are not controlled by the user - they run how they were programmed. User accounts interact with the contract by submitting transactions which execute functions from the contract".
"Arweave has its own version of a smart contract system. SmartWeave is a data-centered protocol built on top of the Arweave blockchain. It is unique because it deploys a lazy evaluation method. In other traditional smart contract systems it is a nodes responsibility to validate the results of a smart contract. SmartWeave's lazy evaluation transfers the burden of computation transaction validation to the smart contract user".
"The SmartWeave approach, on the other hand, has several …

Mark-corrections[7,9,15,19,27,31,33,37,41,58,59,62,]

---

redstone-academy-docs/docs/elementary/arweave.md

"allow entire web applications to function".

Mark-corrections[38]

---

redstone-academy-docs/docs/elementary/blockchain.md

"manipulate blockchain data in a malicious way".

Mark-corrections[19]

---

warp-academy-ardit/final/.gitignore
warp-academy-ardit/final/contract/src/contracts/actions/read/readMessage.ts
warp-academy-ardit/final/contract/src/contracts/actions/write/postMessage.ts
warp-academy-ardit/final/contract/src/contracts/actions/write/voting.ts
warp-academy-ardit/final/contract/src/contracts/contract.ts
warp-academy-ardit/final/contract/src/tools/deploy-contract.ts
warp-academy-ardit/final/contract/tsconfig.json
warp-academy-docs/tutorials/ardit/implementation/handle.md
warp-academy-docs/tutorials/ardit/implementation/post-message.md
warp-academy-docs/tutorials/ardit/implementation/read-message.md
warp-academy-docs/tutorials/ardit/implementation/voting.md

Contract functions were unnecessarily asynchronous + minor fixes.

fix: remove async from contract functions

---

warp-academy-docs/docs/sdk/advanced/bundled-contract.md
warp-academy-docs/docs/sdk/advanced/bundled-interaction.md
warp-academy-docs/docs/sdk/advanced/cache.md
warp-academy-docs/docs/sdk/advanced/kv-storage.md

Fix: typos

---

warp-academy-docs/tutorials/ardit/implementation/handle.md

Fix typo in the word "remove".

docs: fix typo

---

warp-academy-docs/standards/atomic-asset.md

atomic_asset_spec_link.md
